linters-settings:
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    #- dupl
    - errcheck
    #- funlen
    # Will require refactoring to remove three init funcs:
    #- gochecknoinits
    # Likely just remove:
    #- goconst
    #- gocritic
    - gocyclo
    - gofmt
    - goimports
    #- golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    #- lll
    - maligned
    - misspell
    - nakedret
    #- scopelint
    - staticcheck
    - structcheck
    # Will require lots of refactoring Ip to IP in var names:
    #- stylecheck
    - typecheck
    - unconvert
    #- unparam
    - unused
    - varcheck
    - whitespace
